

[package]
name        = "vitte-unicode"
description = "Utilitaires Unicode pour Vitte : normalisation, casefold, segmentation (mots/graphèmes), BiDi, largeur d’affichage."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
documentation = "https://docs.rs/vitte-unicode"

keywords   = ["unicode", "normalization", "segmentation", "bidi", "width"]
categories = ["text-processing", "internationalization", "development-tools"]

[lib]
name = "vitte_unicode"
path = "src/lib.rs"

[features]
# Par défaut : std + segmentation graphemes + normalisation NFC/NFKC + width
default        = ["std", "segmentation", "normalization", "width"]
std            = []
# Segmentation simple via unicode-segmentation (graphemes, words)
segmentation   = ["dep:unicode-segmentation"]
# Normalisation + casefold via unicode-normalization
normalization  = ["dep:unicode-normalization"]
# Bidirectionnel
bidi           = ["dep:unicode-bidi"]
# Largeur d’affichage (East Asian width)
width          = ["dep:unicode-width"]
# Sérialisation optionnelle
serde          = ["dep:serde", "dep:serde_json"]
# Alternatives ICU4X (plus lourdes) en option
icu            = ["dep:icu_normalizer", "dep:icu_segmenter", "dep:icu_properties"]

[dependencies]
thiserror = "1.0"
cfg-if    = "1.0"

# Base
unicode-segmentation = { version = "1.11", optional = true }
unicode-normalization = { version = "0.1", optional = true }
unicode-bidi = { version = "0.3", optional = true }
unicode-width = { version = "0.1", optional = true }

# ICU4X (optionnel)
icu_normalizer = { version = "1.5", optional = true }
icu_segmenter  = { version = "1.5", optional = true }
icu_properties = { version = "1.5", optional = true }

# Sérialisation
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

[dev-dependencies]
pretty_assertions = "1.4"
serde_json = "1"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "segmentation", "normalization", "bidi", "width", "icu", "serde"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all      = "warn"
pedantic = "warn"