

[package]
name        = "vitte-matlab"
description = "Interop Matlab pour Vitte (MEX, Engine API, conversions Rust <-> Matlab)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-matlab"

keywords   = ["matlab", "ffi", "mex", "engine", "interop"]
categories = ["api-bindings", "development-tools", "external-ffi-bindings"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_matlab"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[features]
default = ["std"]
std     = []
serde   = ["dep:serde", "dep:serde_json"]
engine  = []
mex     = []

[dependencies]
thiserror = "1.0"
cfg-if    = "1.0"
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

[dev-dependencies]
serial_test = "3"
pretty_assertions = "1.4"