[package]
name = "vitte-runtime"
version = "0.1.0"
description = "Runtime Vitte : exécution du bytecode et services système (MVP)."
# Hérite des métadonnées du workspace
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
repository.workspace    = true
homepage.workspace      = true
documentation.workspace = true
keywords.workspace      = true
categories.workspace    = true

[lib]
path = "src/lib.rs"

# ───────── Features
[features]
# std activée par défaut (désactive avec --no-default-features)
default = ["std"]
std = []

# Sérialisation optionnelle, relaie vers vitte-core
serde = ["dep:serde", "vitte-core/serde"]

# Intégration VM complète (facultative)
vm = ["dep:vitte-vm"]

# Mode async (facultatif) : boucle/IO via tokio
async = ["dep:tokio"]

# Tracing optionnel
tracing = ["dep:tracing"]

# ───────── Dépendances
[dependencies]
# Workspace deps
anyhow  = { workspace = true }
serde   = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tokio   = { workspace = true, optional = true }  # les features tokio viennent déjà du workspace

# Crates internes
vitte-core = { path = "../vitte-core" }
vitte-vm   = { path = "../vitte-vm", optional = true }

[package.metadata.docs.rs]
all-features = true
