[package]
name = "vitte-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
description = "Cœur du langage Vitte : bytecode, ASM/DISASM, loader, utilitaires."
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://github.com/vitte-lang/vitte"
authors = ["Vincent <you@example.com>"]
categories = ["compilers", "parsing", "virtualization"]
keywords = ["vitte", "bytecode", "vm", "compiler", "asm"]

[lib]
name = "vitte_core"
path = "src/lib.rs"
crate-type = ["rlib"]

# ──────────────────────────────────────────────────────────────────────────────
# FEATURES
# Par défaut: "std" + "serde" ⇒ confort maximal.
# "alloc-only" pour no_std(+alloc). "postcard" conseillée en no_std.
# "zstd" active la compression/décompression dans le loader.
# ──────────────────────────────────────────────────────────────────────────────
[features]
default = ["std", "serde"]

# Active l’écosystème std et les deps qui en ont besoin.
std = [
    "dep:thiserror",
    "dep:bincode",
    "serde/std",
]

# Mode embarqué : no_std(+alloc). N’active PAS "std".
alloc-only = []

# Sérialisation via serde (no_std-friendly quand std est OFF).
serde = ["dep:serde"]

# Sérialisation binaire no_std (plutôt avec alloc-only).
postcard = ["dep:postcard"]

# Compression zstd pour le loader (save/load).
zstd = ["dep:zstd"]

# ──────────────────────────────────────────────────────────────────────────────
# DÉPENDANCES
# ──────────────────────────────────────────────────────────────────────────────
[dependencies]
# Erreurs ergonomiques (std uniquement)
thiserror = { version = "1", optional = true }

# Sérialisation générique (derive). default-features = false pour no_std.
serde = { version = "1", features = ["derive"], default-features = false, optional = true }

# Sérialisation binaire std
bincode = { version = "1.3", optional = true }

# Sérialisation binaire no_std
postcard = { version = "1", default-features = false, optional = true }

# Compression optionnelle
zstd = { version = "0.13", optional = true }

# ──────────────────────────────────────────────────────────────────────────────
# DEV-DEPS (tests/doc en environnement std)
# ──────────────────────────────────────────────────────────────────────────────
[dev-dependencies]
serde_json = "1"
pretty_assertions = "1"

# ──────────────────────────────────────────────────────────────────────────────
# DOCS.RS : construire la doc en mode "std" par défaut
# ──────────────────────────────────────────────────────────────────────────────
[package.metadata.docs.rs]
all-features = false
features = ["std", "serde"]
no-default-features = false
rustdoc-args = ["--cfg", "docsrs"]
