# These are supported funding model platforms

github: [vincent-roussov]   # Ton identifiant GitHub Sponsors (jusqu’à 4 possibles)
patreon: roussov            # Ton username Patreon
open_collective: vitte-lang # Open Collective de ton projet
ko_fi: vincentdev           # Ton Ko-fi username
issuehunt: vitte-lang       # Projet sur IssueHunt
lfx_crowdfunding: vitte     # Projet sur LFX Crowdfunding
polar: vitte                # Polar username
