# These are supported funding model platforms

github: [vincent-roussov]   # Ton identifiant GitHub Sponsors (jusqu’à 4 possibles)
patreon: roussov            # Ton username Patreon
open_collective: vitte-lang # Open Collective de ton projet
ko_fi: vincentdev           # Ton Ko-fi username
tidelift: npm/vitte         # Exemple : tidelift pour un package npm
community_bridge: vitte     # Nom du projet Community Bridge
liberapay: vincent_r        # Ton Liberapay username
issuehunt: vitte-lang       # Projet sur IssueHunt
lfx_crowdfunding: vitte     # Projet sur LFX Crowdfunding
polar: vitte                # Polar username
buy_me_a_coffee: vincent    # Ton Buy Me a Coffee username
thanks_dev: vitte           # thanks.dev username
custom: ['https://vitte.dev/donate', 'https://paypal.me/vincent']
