[package]
name = "vitte-grammar"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
name = "vitte_grammar"
path = "src/lib.rs"

[dependencies]
pest = "2.7"
pest_derive = "2.7"
thiserror = { workspace = true }
smol_str = "0.1"
