[workspace]
members = [
    "crates/vitte-ast",
    "crates/vitte-compiler",
    "crates/vitte-cli"
]
resolver = "2"

# Exclure certains dossiers si besoin (ex: docs, scripts)
exclude = [
    "target",
    ".github"
]

[workspace.package]
# Métadonnées globales
version = "0.1.0"
edition = "2021"
authors = ["Vincent <ton_email@exemple.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://vitte-lang.github.io/vitte/"
documentation = "https://docs.rs/vitte"
readme = "README.md"

[workspace.dependencies]
# Dépendances partagées entre crates
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pretty_assertions = "1.4"
thiserror = "2.0.16"
zstd = "0.13"

[workspace.metadata.release]
# Configuration pour cargo-release (si tu veux versionner proprement)
tag-prefix = "v"
sign-commits = true
sign-tags = true
push-remote = "origin"
