[package]
name = "vitte-cli"
version = "0.1.0"
edition = "2021"
description = "CLI lib for Vitte"

[features]
# On active le parsing TOML par défaut
default = ["toml"]

# Les features exposent proprement les deps optionnelles
toml = ["dep:toml"]
core = ["dep:vitte-core"]
vm = ["dep:vitte-vm"]
compiler = ["dep:vitte-compiler"]

[dependencies]
anyhow = "1"
camino = "1"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }

# Dépendances optionnelles (mappées aux features ci-dessus)
toml = { version = "0.8", features = ["parse"], optional = true }
vitte-core = { path = "../vitte-core", optional = true }
vitte-vm = { path = "../vitte-vm", optional = true }
vitte-compiler = { path = "../vitte-compiler", optional = true }
