# rust-toolchain.toml — Toolchain figé & composants stables
# Objectif : builds reproductibles, DX solide, CI tranquille.

[toolchain]
# Monte à 1.82.0 pour éviter les soucis MSRV (backtrace/home).
channel = "1.82.0"

# Minimal = cargo + rustc + std : rapide, prévisible
profile = "minimal"

# Composants utiles et stables
components = [
  "rustfmt",             # formatage
  "clippy",              # lints
  "rust-src",            # sources std (no_std, RA, build-std, etc.)
  "llvm-tools-preview",  # objdump/size/addr2line via cargo-binutils
]

# ⚠️ Ne liste PAS de targets ici : certaines ne sont pas dispo partout
# et l’installation échoue en bloc. Installe-les “à la demande” (script/CI).
