

# rust-toolchain.toml — Vitte workspace (standardisé, stable)

[toolchain]
# Utilise la dernière toolchain stable installée sur le système.
channel = "stable"
profile = "default"

# Outils indispensables pour un repo de développement complet.
components = [
  "rustfmt",
  "clippy",
  "rust-src",
  "llvm-tools-preview",
  "rust-analyzer"
]

# Cibles cross-compile supportées.
targets = [
  # Linux (glibc + musl + ARM/RISC-V)
  "x86_64-unknown-linux-gnu",
  "i686-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "arm-unknown-linux-gnueabihf",
  "armv7-unknown-linux-gnueabihf",
  "riscv64gc-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",

  # Apple (macOS + iOS + iPadOS + tvOS)
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "aarch64-apple-ios",
  "aarch64-apple-ios-sim",
  "x86_64-apple-ios",

  # Windows (MSVC + GNU + ARM)
  "x86_64-pc-windows-msvc",
  "i686-pc-windows-msvc",
  "aarch64-pc-windows-msvc",
  "x86_64-pc-windows-gnu",
  "i686-pc-windows-gnu",

  # BSD (NetBSD)
  "x86_64-unknown-netbsd",
  

  # Raspberry Pi (ARMv6, ARMv7, ARM64)
  "arm-unknown-linux-musleabihf",
  "arm-unknown-linux-gnueabi",
  "armv7-unknown-linux-gnueabihf",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",

  # WebAssembly
  "wasm32-unknown-unknown",
]