# rust-toolchain.toml — Toolchain pin + composants stables
# Objectif : builds reproductibles et CI sereine.

[toolchain]
# ⚓ Fige la version de Rust (pinning) pour éviter les surprises.
channel = "1.80.0"
# Installe le strict nécessaire (cargo, rustc, rust-std).
profile = "minimal"

# Composants indispensables (stables, disponibles partout).
components = [
  "rustfmt",
  "clippy",
  "rust-src",   # utile pour build-std, analyzers, docs locales avancées
]

# ✅ Ne pas lister de cibles ici (certaines indisponibles en binaire → échecs d’insta).
#    Ajoute-les dans la CI / scripts *au moment où tu en as besoin*, ex. :
#      rustup target add wasm32-unknown-unknown
#      rustup target add wasm32-wasi
#      rustup target add thumbv7em-none-eabi
#    Pour x86_64-unknown-none (bare-metal), préfère `-Z build-std` côté build plutôt
#    qu’un ajout global ici.
