# rustfmt.toml — Minimal public style (Rust 1.80+)

edition = "2021"
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

# Imports
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Comments
wrap_comments = true
comment_width = 100

