# .rustfmt.toml — Stable-safe (Rust 1.80)

# ——— Base ———
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"

# ——— Imports & modules ———
reorder_imports = true
imports_granularity = "Crate"      # "Module" ou "Item" au besoin
group_imports = "StdExternalCrate" # groupe: std | extern | crate/local
reorder_modules = true

# ——— Commentaires & docs ———
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
normalize_doc_attributes = true

# ——— Macros ———
format_macro_bodies = true
# (format_macro_matchers retiré: parfois instable selon versions)

# ——— Virgules & opérateurs ———
trailing_comma = "Vertical"
# (match_block_trailing_comma / match_arm_leading_pipes / binop_separator retirés pour compat stable)

# ——— Blancs ———
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0

# ——— Littéraux & espaces ———
hex_literal_case = "Lower"
spaces_around_ranges = false

# ——— Alignements ———
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# ——— Largeurs fines ———
array_width = 80
attr_fn_like_width = 70
chain_width = 80
fn_call_width = 80
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
struct_lit_width = 40
struct_variant_width = 40

# ——— Choix assumés ———
fn_single_line = false

