# rust-toolchain.toml — Toolchain pin + composants stables
# Objectif: builds reproductibles, CI sereine.

[toolchain]
channel = "1.80.0"     # version figée (recommandé pour la CI)
profile = "minimal"    # installe le strict nécessaire

# Composants indispensables (stables, dispo partout)
components = [
  "rustfmt",
  "clippy",
  "rust-src"
]

# 💡 IMPORTANT
# On n’ajoute PAS ici de cibles cross. Certaines ne sont pas dispo en binaire sur toutes
# plateformes et font échouer l’installation automatique. Ajoute-les dans la CI/job au besoin :
#   rustup target add wasm32-unknown-unknown
#   rustup target add wasm32-wasi
#   rustup target add thumbv7em-none-eabi
# (et pour bare-metal x86_64-unknown-none, préfère `-Z build-std` côté build plutôt qu’ici)
