[project]
name = "vitte"
license = "Apache-2.0"
description = "Vitte unified workspace: compiler, stdlib, tooling, CLI."

[build]
rust_version = "1.82.0"
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "aarch64-apple-darwin",
  "aarch64-pc-windows-msvc"
]
features = ["engine", "fmt", "modules"]

[dependencies]
stdlib = { module = "vitte-stdlib", version = "0.1.0" }
http = { module = "modules/http_client", version = "0.2.0" }
