

[package]
name        = "vitte-semver"
description = "Outils SemVer pour Vitte : parsing, comparaison, incréments de version, compatibilité."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
documentation = "https://docs.rs/vitte-semver"

keywords   = ["semver", "versioning", "parsing", "compatibility"]
categories = ["development-tools", "parsing"]

[lib]
name = "vitte_semver"
path = "src/lib.rs"

[features]
default = ["std", "serde"]
std     = []
serde   = ["dep:serde", "dep:serde_json"]

[dependencies]
thiserror = "1.0"
cfg-if    = "1.0"
semver    = "1.0"

# Sérialisation
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

[dev-dependencies]
pretty_assertions = "1.4"
serde_json = "1"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "serde"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all      = "warn"
pedantic = "warn"