[package]
name         = "vitte-go"
description  = "Interop Go pour Vitte (FFI, bindings et génération de stubs)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"

[lib]
name       = "vitte_go"
crate-type = ["cdylib", "rlib"]

[features]
default = ["std"]
std     = []
cbind   = ["cbindgen"]

[dependencies]
# Génération FFI C compatible (utilisable côté Go via cgo)
libc = "0.2"

# Optionnel : génération headers C automatiques pour Go
cbindgen = { version = "0.27", optional = true }

# Gestion erreurs
thiserror = "1"

[build-dependencies]
# Pour générer un .h via build.rs si feature "cbind"
cbindgen = { version = "0.27", optional = true }

[dev-dependencies]
tempfile = "3"