

[package]
name        = "vitte-logs"
description = "Système de logs unifié pour Vitte (backend agnostique, macros, intégrations tracing/log)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-logs"

keywords   = ["logging", "tracing", "macros", "log", "instrumentation"]
categories = ["development-tools", "debugging"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_logs"
path = "src/lib.rs"

[features]
default = ["std", "macros"]
std     = []
macros  = []
tracing = ["dep:tracing"]
log     = ["dep:log"]

[dependencies]
thiserror = "1.0"
cfg-if    = "1.0"
tracing   = { version = "0.1", optional = true, default-features = false, features = ["std", "attributes"] }
log       = { version = "0.4", optional = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
pretty_assertions  = "1.4"