

[package]
name        = "vitte-new"
description = "Outil de scaffolding pour Vitte : création rapide de crates, templates et fichiers standard."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"

keywords   = ["scaffold", "template", "cli", "generator"]
categories = ["development-tools"]

[lib]
name = "vitte_new"
path = "src/lib.rs"

[[bin]]
name = "vitte-new"
path = "src/main.rs"

[features]
default = ["std"]
std     = []
serde   = ["dep:serde", "dep:serde_json"]

[dependencies]
anyhow      = "1.0"
clap        = { version = "4.5", features = ["derive"] }
camino      = "1.1"
fs-err      = "2.11"
toml_edit   = "0.22"
ignore      = "0.4"
include_dir = "0.7"
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "serde"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all      = "warn"
pedantic = "warn"