[package]
name        = "vitte-harness"
description = "Infrastructure de test et de benchmarks pour le projet Vitte."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["testing", "harness", "bench", "vitte"]
categories = ["development-tools", "testing"]

[lib]
name = "vitte_harness"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Extensions prévues
benches = []
integration = []

# Activer toutes les capacités
full = ["std", "benches", "integration"]

[dependencies]
criterion = { version = "0.5", optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
too_many_lines          = "allow"
doc_markdown            = "allow"
