[package]
name = "vitte-project"
description = "Gestion de projets Vitte (manifeste, dépendances, workspaces, build)."
documentation = "https://docs.rs/vitte-project"
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["compiler", "project", "workspace", "build", "vitte"]
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
categories = ["development-tools", "compilers"]
exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_project"
path = "src/lib.rs"

[features]
default = ["std"]
full = ["std", "json", "toml"]
json = ["dep:serde", "dep:serde_json"]
std = []
toml = ["dep:serde", "dep:toml"]

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
toml = { version = "0.8", optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = "3.12"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
doc_markdown = "allow"
module_name_repetitions = "allow"
nursery = "warn"
pedantic = "warn"
too_many_lines = "allow"