[dependencies]
anyhow = "1"
vitte-core = { path = "../vitte-core" }
vitte-compiler = { path = "../vitte-compiler", optional = true }
once_cell = { version = "1", optional = true }

[features]
default = ["compiler","cache"]
compiler = ["vitte-compiler"]
cache = ["once_cell"]
