[package]
name        = "vitte-man"
description = "vitte-man — génération de pages man (troff/groff mdoc/man) pour les CLIs Vitte."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["cli", "man", "manual", "groff", "mdoc"]
categories = ["command-line-interface", "development-tools"]

[lib]
name = "vitte_man"
path = "src/lib.rs"

[features]
default = ["std", "errors", "args-spec"]

std        = []
alloc-only = []
serde      = ["dep:serde"]
errors     = ["dep:thiserror"]

# Intégration directe avec specs d’arguments
args-spec  = ["dep:vitte-args"]

[dependencies]
serde     = { workspace = true, optional = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true, optional = true }

# interne
vitte-args = { path = "../vitte-args", version = "0.1.0", optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "errors", "args-spec", "serde"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"