[package]
name        = "vitte-borrock"
description = "Experimental borrock engine for the Vitte language (sandbox, research, prototypes)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-borrock"

keywords   = ["vitte", "borrock", "engine", "experimental"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_borrock"
path = "src/lib.rs"

[[bin]]
name = "vitte-borrock"
path = "src/main.rs"

[features]
default = ["std"]
std     = []

# Mode prototypage complet
full = ["std"]

[dependencies]
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
toml        = "0.8"
thiserror   = "1"
log         = "0.4"
env_logger  = "0.11"
rayon       = "1"
anyhow      = "1"