[package]
name        = "vitte-codegen-wasm64"
description = "WebAssembly 64-bit backend for Vitte (wasm64, simd128/threads optional)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-codegen-wasm64"

keywords   = ["compiler", "codegen", "wasm", "wasm64", "vitte"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_codegen_wasm64"
path = "src/lib.rs"

[features]
default      = ["std"]
std          = []
simd128      = []     # enable SIMD encodings (wasm simd128)
threads      = []     # enable atomics/threading encodings
ref_types    = []     # reference types encodings
bulk_memory  = []     # bulk memory ops
full         = ["std", "simd128", "threads", "ref_types", "bulk_memory"]

[dependencies]
vitte-core    = { path = "../vitte-core", version = "0.1.0" }
vitte-ir      = { path = "../vitte-ir", version = "0.1.0" }
vitte-runtime = { path = "../vitte-runtime", version = "0.1.0" }