[package]
name = "vitte-lsp"
version = "0.1.0"
edition = "2021"
description = "Serveur LSP (Language Server Protocol) pour le langage Vitte"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://vitte-lang.github.io/vitte/"
readme = "../../README.md"

[lib]
name = "vitte_lsp"
path = "src/lib.rs"

[[bin]]
name = "vitte-lsp"
path = "src/main.rs"

[dependencies]
# LSP infra
tower-lsp = "0.20"
tokio = { version = "1.39", features = ["full"] }

# crates internes
vitte-core = { path = "../vitte-core", version = "0.1.0" }
vitte-lexer = { path = "../vitte-lexer", version = "0.1.0" }

# utilitaire pour les erreurs
anyhow = "1.0"

[dev-dependencies]
pretty_assertions = "1.4"
