[package]
name        = "vitte-book"
description = "Documentation builder and book generator for the Vitte language (md → HTML/PDF/EPUB)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-book"

keywords   = ["vitte", "book", "documentation", "mdbook"]
categories = ["development-tools", "documentation"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_book"
path = "src/lib.rs"

[[bin]]
name = "vitte-book"
path = "src/main.rs"

[features]
default = ["std"]
std     = []

html  = []
pdf   = []
epub  = []
all   = ["html", "pdf", "epub"]

[dependencies]
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
toml        = "0.8"
clap        = { version = "4", features = ["derive"] }
walkdir     = "2"
pulldown-cmark = "0.10"
rayon       = "1"
thiserror   = "1"

# optionnels pour les sorties
printpdf    = { version = "0.7", optional = true }
epub-builder = { version = "0.6", optional = true }