[package]
name        = "vitte-compiler"
description = "Compilateur Vitte : passes (collecte, typage), table des symboles, diagnostics, et émission de bytecode."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-compiler"

keywords   = ["compiler", "language", "bytecode", "vitte"]
categories = ["compilers", "development-tools", "parser-implementations"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_compiler"
path = "src/lib.rs"

[features]
# Par défaut : std (I/O utilitaires, etc.)
default = ["std"]

# Support std. En no_std: `--no-default-features`.
std = []

# Sérialisation interne (si tu derives/exports des structures)
serde = ["dep:serde"]

# Compression de la section CODE (si ton émetteur compresse).
zstd = ["dep:zstd"]

# Backend VITBC (utilise le crate vitte-vitbc comme émetteur)
vitbc-backend = ["dep:vitte-vitbc"]

# Combo pratique: backend VITBC + zst
