[package]
name = "vitte-compiler"
version = "0.1.0"
edition = "2021"
authors = ["Vincent <ton_email@exemple.com>"]
description = "Compilateur du langage Vitte : passes (collecte, typage), table des symboles, diagnostics, et génération de bytecode VITBC."
license = "MIT OR Apache-2.0"
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://vitte-lang.github.io/vitte/"
documentation = "https://docs.rs/vitte-compiler"
readme = "README.md"
keywords = ["compiler", "language", "bytecode", "vitte"]
categories = ["compilers", "no-std", "parser-implementations"]
exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_compiler"
path = "src/lib.rs"

[features]
# std est activé par défaut
default = ["std"]

# Support std (I/O, write_to_file, etc.)
std = []

# Active la sérialisation interne (serde derive)
serde = ["dep:serde"]

# Compression de la section CODE via zstd
zstd = ["dep:zstd"]

# Full = tout
full = ["std", "serde", "zstd"]

[dependencies]
# Dépendance vers ton AST
vitte-ast = { path = "../vitte-ast", version = "0.1.0" }

# Serde (optionnel)
serde = { version = "1.0", features = ["derive"], optional = true }

# Compression zstd (optionnelle, seulement si tu actives la feature zstd)
zstd = { version = "0.13", optional = true }

# Pour jolis messages d'erreur (facultatif mais pratique)
thiserror = { version = "2.0.16", optional = true }

[dev-dependencies]
serde_json = "1.0"
pretty_assertions = "1.4"
