

[package]
name = "vitte-bin"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Rousseau <roussov@users.noreply.github.com>"]
description = "Vitte binary CLI orchestrator — engine delegation, REPL, run/compile wrapper"
license = "MIT"
repository = "https://github.com/vitte-lang/vitte"
readme = "README.md"
keywords = ["vitte", "cli", "engine", "compiler", "repl"]
categories = ["command-line-utilities", "development-tools"]

[lib]
name = "vitte_bin"
path = "src/lib.rs"

[[bin]]
name = "vitte-bin"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "cargo", "wrap_help"] }
log = "0.4"
env_logger = "0.11"
which = "6.0"
vitte-cli = { path = "../vitte-cli", package = "vitte-cli" }

[features]
default = []
engine = []
gui = []
server = []
experimental = []
cli = []