

[package]
name        = "vitte-loader"
description = "Chargeur dynamique et gestionnaire de modules pour Vitte (plugins, bibliothèques partagées, symboles dynamiques)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-loader"

keywords   = ["loader", "dynamic", "plugin", "ffi", "runtime"]
categories = ["development-tools", "os::unix-apis", "os::windows-apis"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_loader"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []
serde   = ["dep:serde", "dep:serde_json"]

[dependencies]
thiserror   = "1.0"
cfg-if      = "1.0"
libloading  = "0.8"
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

[dev-dependencies]
pretty_assertions = "1.4"