[package]
name = "vitte-dap"
version = "0.1.0"
edition = "2021"
description = "Vitte Debug Adapter Protocol (DAP) server over stdio"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://vitte-lang.github.io/vitte/"
readme = "../../README.md"

# Le binaire (ex: src/main.rs lance DummyBackend ou la vraie VM)
[[bin]]
name = "vitte-dap"
path = "src/main.rs"

[features]
# std activée par défaut
default = ["std"]
std = []
serde = ["dep:serde"]

[dependencies]
# Dépendances internes
vitte-core = { path = "../vitte-core", version = "0.1.0" }
vitte-ast = { path = "../vitte-ast", version = "0.1.0" }
vitte-compiler = { path = "../vitte-compiler", version = "0.1.0" }

# Sérialisation JSON
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = "1.0"

# Utilitaires
thiserror = "2.0.16"

[dev-dependencies]
pretty_assertions = "1.4"
