[package]
name        = "vitte-crypto"
description = "Cryptography utilities for Vitte (AEAD, hashes, KDFs, signatures, key exchange)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-crypto"

keywords   = ["crypto", "aead", "hash", "kdf", "signature"]
categories = ["cryptography", "algorithms"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_crypto"
path = "src/lib.rs"

[features]
default   = ["std", "rand", "zeroize"]
std       = []
rand      = ["dep:rand_core", "dep:getrandom"]
zeroize   = ["dep:zeroize"]

# Hashes
blake3    = ["dep:blake3"]
sha3      = ["dep:sha3"]

# AEADs
aes-gcm          = ["dep:aes-gcm", "dep:aes", "dep:ctr"]
chacha20poly1305 = ["dep:chacha20poly1305"]

# KDFs
hkdf     = ["dep:hkdf"]
pbkdf2   = ["dep:pbkdf2"]
argon2   = ["dep:argon2"]

# Signatures / KEM
ed25519  = ["dep:ed25519-dalek"]
x25519   = ["dep:x25519-dalek"]

# All-in
full = [
  "std","rand","zeroize",
  "blake3","sha3",
  "aes-gcm","chacha20poly1305",
  "hkdf","pbkdf2","argon2",
  "ed25519","x25519"
]

[dependencies]
vitte-core = { path = "../vitte-core", version = "0.1.0" }

# randomness + memory hygiene
rand_core  = { version = "0.6", optional = true, default-features = false }
getrandom  = { version = "0.2", optional = true, default-features = false, features = ["std"] }
zeroize    = { version = "1",   optional = true, default-features = false, features = ["zeroize_derive"] }

blake3 = { version = "1", optional = true, default-features = false }
sha2   = { version = "0.10", default-features = true }
sha3   = { version = "0.10", optional = true, default-features = false }

# aeads
aes-gcm          = { version = "0.10", optional = true, default-features = false, features = ["alloc"] }
chacha20poly1305 = { version = "0.10", optional = true, default-features = false, features = ["alloc"] }
aes              = { version = "0.8",  optional = true, default-features = false }
ctr              = { version = "0.9",  optional = true, default-features = false }

# kdfs
hkdf   = { version = "0.12", optional = true, default-features = false }
pbkdf2 = { version = "0.12", optional = true, default-features = false }
argon2 = { version = "0.5",  optional = true, default-features = false }

# signatures / key exchange
ed25519-dalek = { version = "2", optional = true, default-features = false, features = ["rand_core"] }
x25519-dalek  = { version = "2", optional = true, default-features = false }

thiserror = { version = "1", default-features = true }
hmac = { version = "0.12", default-features = true }

[dev-dependencies]
hex = "0.4"