[package]
name        = "vitte-fuzz"
description = "Outillage de fuzzing pour les composants du langage Vitte."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["fuzzing", "testing", "vitte"]
categories = ["development-tools", "testing"]

[lib]
name = "vitte_fuzz"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Intégrations futures (libfuzzer, honggfuzz, afl…)
libfuzzer = []
honggfuzz = []
afl       = []

# Tout activer
full = ["std", "libfuzzer", "honggfuzz", "afl"]

[dependencies]

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
too_many_lines          = "allow"
doc_markdown            = "allow"
