[package]
name        = "vitte-cxx"
description = "C++ interop for Vitte (FFI bindings, cxx-bridge, inline C++ utilities)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-cxx"

keywords   = ["ffi", "cxx", "interop", "bindings"]
categories = ["development-tools", "ffi"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_cxx"
path = "src/lib.rs"

[features]
default   = ["std", "cxx-bridge"]
std       = []
cxx-bridge = ["dep:cxx"]

full = ["std", "cxx-bridge"]

[dependencies]
thiserror = "2.0.17"
# cxx crate for safe C++ interop
cxx = { version = "1", optional = true }

[build-dependencies]
cc = "1.0"

[dev-dependencies]
tempfile = "3"