

[package]
name        = "vitte-sym"
description = "Symboles et interning pour Vitte : interner de chaînes, IDs stables, sérialisation, tables thread-safe."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
documentation = "https://docs.rs/vitte-sym"

keywords   = ["symbol", "intern", "ids", "serde", "hash"]
categories = ["data-structures", "parsing", "development-tools"]

[lib]
name = "vitte_sym"
path = "src/lib.rs"

[features]
# Par défaut: std + sérialisation
default = ["std", "serde"]
std     = []
# Sérialisation et formats binaires
serde   = ["dep:serde"]
bincode = ["dep:bincode"]
# Choix du hasher (par défaut ahash)
ahash   = ["dep:ahash"]
rustc-hash = ["dep:rustc-hash"]

[dependencies]
thiserror = "1.0"
cfg-if    = "1.0"
parking_lot = "0.12"

# Interner de chaînes haut-niveau
string-interner = "0.14"

# Hashers
ahash       = { version = "0.8", optional = true }
rustc-hash  = { version = "1.1", optional = true }

# Sérialisation
serde       = { version = "1", features = ["derive"], optional = true }
bincode     = { version = "1.3", optional = true }

[dev-dependencies]
pretty_assertions = "1.4"
serde_json = "1"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "serde", "bincode", "ahash", "rustc-hash"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all      = "warn"
pedantic = "warn"