[package]
name        = "vitte-macro"
description = "Macros procédurales et derive macros pour Vitte (aides de compilation et génération de code)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-macro"

keywords   = ["compiler", "macro", "proc-macro", "vitte"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
proc-macro = true
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Sérialisation (export metadata macros)
serde = ["dep:serde"]

# Tout activé
full = ["std", "serde"]

[dependencies]
proc-macro2 = "1.0"
quote       = "1.0"
syn         = { version = "2.0", features = ["full"] }

serde = { workspace = true, features = ["derive"], optional = true }

anyhow = "1.0"

[dev-dependencies]
trybuild          = "1.0"
pretty_assertions = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"