[package]
name        = "vitte-buildkit"
description = "Build system toolkit for the Vitte language (tasks, pipelines, packaging)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-buildkit"

keywords   = ["vitte", "build", "pipeline", "toolkit"]
categories = ["development-tools", "build-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_buildkit"
path = "src/lib.rs"


[features]
default = ["std"]
std     = []

# active toutes les extensions
full = ["std"]

[dependencies]
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
toml        = "0.8"
thiserror   = "1"
rayon       = "1"
walkdir     = "2"
clap        = { version = "4", features = ["derive"] }
log         = "0.4"
env_logger  = "0.11"
anyhow      = "1"