[package]
name        = "vitte-cap"
description = "Gestion des capacités, permissions et sandboxing pour Vitte"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-cap"

keywords   = ["vitte", "security", "capabilities", "sandbox", "permissions"]
categories = ["compilers", "development-tools", "security"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_cap"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std     = []
# Mode stricte sans std (no_std, embedded)
no_std  = []

[dependencies]
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
thiserror    = "1"
bitflags     = "2"

[dev-dependencies]
tempfile = "3"