[package]
name        = "vitte-codegen"
description = "Génération de code pour Vitte (IR → backends: Cranelift, LLVM, ASM)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-codegen"

keywords   = ["compiler", "codegen", "backend", "vitte"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_codegen"
path = "src/lib.rs"

[features]
default          = ["std", "asm"]
std              = []
cli = []

# Sélection des backends
asm              = ["vitte-asm"]
cranelift        = ["vitte-backend-cranelift"]
llvm             = ["vitte-backend-llvm"]

# Cibles CPU
x86_64           = []
aarch64          = []

# Mode debug étendu (traces IR, dumps)
debug-dumps      = []

# Tout activé
full             = ["std", "asm", "cranelift", "llvm", "x86_64", "aarch64", "debug-dumps"]

[dependencies]
vitte-ir                = { path = "../vitte-ir" }
vitte-errors            = { path = "../vitte-errors" }
vitte-asm               = { path = "../vitte-asm", optional = true }
vitte-backend-cranelift = { path = "../vitte-backend-cranelift", optional = true }
vitte-backend-llvm      = { path = "../vitte-backend-llvm", optional = true }

target-lexicon = "0.12"
itertools      = "0.13"
bitflags       = "2.6"

serde      = { workspace = true, optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
insta             = "1.41"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"

[[bin]]
name = "vitte-codegen"
path = "src/main.rs"