[package]
name        = "vitte-ecs"
description = "Entity-Component-System (ECS) framework for Vitte runtime and tools."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-ecs"

keywords   = ["ecs", "entity", "component", "system", "game-dev"]
categories = ["game-engines", "data-structures"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_ecs"
path = "src/lib.rs"

[features]
default   = ["std"]
std       = []
serde     = ["dep:serde", "dep:serde_json"]
parallel  = ["dep:rayon"]

full      = ["std","serde","parallel"]

[dependencies]
vitte-core = { path = "../vitte-core", version = "0.1.0" }

thiserror  = { version = "1", default-features = false }
hashbrown  = "0.15"

# optional
serde      = { version = "1", optional = true, features = ["derive"] }
serde_json = { version = "1", optional = true }
rayon      = { version = "1", optional = true }

[dev-dependencies]
rand       = "0.8"