[features]
default = ["std"]
std = ["dep:thiserror", "dep:bincode"]
alloc-only = []

serde      = ["dep:serde"]
postcard   = ["dep:postcard"]
tracing    = ["dep:tracing"]        # si tu veux réactiver tracing plus tard
eval       = []                      # runtime/…
compiler   = []                      # compiler/…
time-crate = ["dep:time"]

[dependencies]
thiserror = { version = "1", optional = true }
serde     = { version = "1", features = ["derive"], default-features = false, optional = true }
bincode   = { version = "1.3", optional = true }
postcard  = { version = "1", default-features = false, optional = true }
tracing   = { version = "0.1", default-features = false, optional = true }
time      = { version = "0.3", default-features = false, optional = true }
