[package]
name = "vitte-lexer"
version = "0.1.0"
edition = "2021"
description = "Lexer du langage Vitte: identifiants, nombres (2/8/10/16), floats, strings/char avec échappements, commentaires, spans."
license = "MIT OR Apache-2.0"
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://vitte-lang.github.io/vitte/"


[lib]
name = "vitte_lexer"
path = "src/lib.rs"

[features]
# On compile avec la lib standard par défaut
default = ["std"]
# Permet de compiler en no_std: `--no-default-features`
std = []

[dependencies]
# Types de base (Span, Spanned, SourceId, Pos, etc.)
vitte-core = { path = "../vitte-core", version = "0.1.0" }

[dev-dependencies]
pretty_assertions = "1.4"
