[package]
name         = "vitte-golden"
description  = "Framework de tests golden pour Vitte (sortie réelle vs fichiers de référence)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"

[lib]
name = "vitte_golden"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

[dependencies]
# Diff textuel lisible
similar = "2"

# Sérialisation optionnelle
serde      = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

# Erreurs
thiserror = "1"

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1"