[package]
name        = "vitte-clippy"
description = "Linter et analyseur statique de style Clippy pour Vitte"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-clippy"

keywords   = ["vitte", "linter", "analyzer", "clippy", "static-analysis"]
categories = ["development-tools", "compilers", "lint"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_clippy"
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "vitte-clippy"
path = "src/main.rs"

[features]
default = ["std"]
std     = []
full    = ["std"]

[dependencies]
thiserror    = "1"
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
walkdir      = "2"
regex        = "1"
log          = "0.4"
env_logger   = "0.11"
anyhow       = "1"

[dev-dependencies]
tempfile = "3"