[package]
name         = "vitte-gpu"
description  = "Abstractions GPU pour Vitte (rendu et calcul via wgpu)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"

[lib]
name = "vitte_gpu"
path = "src/lib.rs"

[features]
default = ["wgpu/default", "std"]
std     = []
trace   = ["wgpu/trace"]

[dependencies]
wgpu = "0.20"
winit = { version = "0.30", optional = true }
pollster = "0.3"
thiserror = "1"
log = "0.4"

[dev-dependencies]
env_logger = "0.11"