[package]
name = "vitte-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Command-line interface for the Vitte language"
repository = "https://github.com/ton-org/vitte"
readme = "../../README.md"
categories = ["command-line-utilities", "development-tools"]
keywords = ["vitte", "cli", "language"]
# publish=false si c'est interne au mono-repo
# publish = false

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

# Optionnels (activés par features)
vitte-core = { path = "../vitte-core", optional = true }
vitte-compiler = { path = "../vitte-compiler", optional = true }
vitte-vm = { path = "../vitte-vm", optional = true }

[features]
default = []
core = ["vitte-core"]
compiler = ["core", "vitte-compiler"]
vm = ["core", "vitte-vm"]

# Facultatif : binaire installé sous le nom "vitte"
[[bin]]
name = "vitte"
path = "src/main.rs"

