[package]
name         = "stdlib"
version      = "0.1.0"
description  = "Bibliothèque standard du langage Vitte (MVP)."
edition      = "2021"
rust-version = "1.75"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/vitte-lang/vitte"
homepage     = "https://vitte-lang.github.io/vitte/"
documentation = "https://vitte-lang.github.io/vitte/docs"
keywords     = ["vitte", "language", "stdlib", "vm", "bytecode"]
categories   = ["development-tools", "compilers"]

[lib]
path = "src/lib.rs"

[features]
# Par défaut on veut la std
default = ["std"]

# Propage la feature vers vitte-core
std    = ["vitte-core/std"]

# Optionnel : si un jour tu exposes un mode no_std + alloc,
# dé-commente la ligne ci-dessous ET n’active pas "std" en même temps.
# alloc-only = ["vitte-core/alloc-only"]

# Sérialisation optionnelle, relayée vers vitte-core
serde  = ["dep:serde", "vitte-core/serde"]

[dependencies]
anyhow = "1"
serde  = { version = "1", features = ["derive"], optional = true }

# Très important: ne pas forcer les features par défaut de vitte-core,
# pour éviter d'activer "std" quand on build sans défauts.
vitte-core = { path = "../vitte-core", default-features = false }

[package.metadata.docs.rs]
# Évite d'activer *toutes* les features (risque de conflit std/alloc-only).
features = ["std", "serde"]
# Si un jour tu exposes "alloc-only", ne l’ajoute pas ici en même temps que "std".

