[package]
name = "vitte-cli"
version = "0.1.0"
description = "CLI officielle pour le langage Vitte : build, outils, gestion de projets."
publish = false

# Hérite des métadonnées du workspace (définies au Cargo.toml racine)
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
repository.workspace    = true
homepage.workspace      = true
documentation.workspace = true
keywords.workspace      = true
categories.workspace    = true

[[bin]]
name = "vitte"
path = "src/main.rs"

[dependencies]
anyhow             = { workspace = true }
clap               = { workspace = true, features = ["derive"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

# (ajoute d’autres deps au besoin, mais évite les deps internes tant que non utilisées)

# Si tu as un build.rs pour afficher les messages post-build (completions),
# garde cette section ; sinon tu peux la supprimer sans scrupule.
[build-dependencies]
dirs-next = "2"
