# Cargo configuration for the Vitte monorepo
# Docs: https://doc.rust-lang.org/cargo/reference/config.html

[term]
color = "auto"

[build]
# Un seul target-dir pour tout le workspace (plus rapide en CI)
target-dir = "target"

[net]
git-fetch-with-cli = true
retry = 2

# ----- Profiles ----------------------------------------------------------
[profile.dev]
opt-level = 1
debug = true
debug-assertions = true
overflow-checks = true
incremental = true

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = 1        # utile pour symboles perf
strip = "debuginfo"

[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = 1

[profile.test]
opt-level = 0
debug = true
overflow-checks = true

# ----- Env (générique) ---------------------------------------------------
[env]
# Optimise pour la machine locale (safe par défaut)
RUSTFLAGS = "-C target-cpu=native"
RUSTDOCFLAGS = "--cfg docsrs"

# ----- Sources / Registry ------------------------------------------------
# Activer l'index "sparse" (plus rapide & léger)
[source.crates-io]
replace-with = "sparse-index"

[source.sparse-index]
registry = "sparse+https://index.crates.io/"

# (Optionnel) Patch de crates internes pendant le dev local
# [patch.crates-io]
# vitte-core = { path = "crates/vitte-core" }
# vitte-vm   = { path = "crates/vitte-vm" }
# vitte-cli  = { path = "crates/vitte-cli" }

# ----- Aliases -----------------------------------------------------------
[alias]
b = "build --workspace"
r = "run -p vitte-cli --"
t = "test --workspace --all-features"
fmt = "fmt --all"
clippy = "clippy --workspace --all-features -- -D warnings"
doc = "doc --workspace --all-features --no-deps"
bench = "bench --workspace"
release = "build --workspace --release"

# WASM helpers
# Requiert nightly si vous utilisez -Z build-std
wasm = "build --target wasm32-unknown-unknown -p vitte-core"
wasm-wasi = "build --target wasm32-wasi -p vitte-core"

# ----- Runners / Targets -------------------------------------------------
[target.wasm32-wasi]
# Exécuter `cargo run --target wasm32-wasi -p vitte-core` via wasmtime
runner = "wasmtime run --dir=."

[target.wasm32-unknown-unknown]
# Panic abort recommandé côté wasm "bare" (pas de std)
rustflags = ["-C", "panic=abort"]

# Exemple de config Linux (décommentez si vous avez lld)
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Mac (LLVM ld64 par défaut — généralement ok)
# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-Wl,-dead_strip"]

# ----- Include overrides -------------------------------------------------
# Cargo fusionne automatiquement config.local.toml si présent dans ce dossier.
