[package]
name         = "vitte-incremental"
description  = "Infrastructure de compilation incrémentale pour Vitte (dépendances, hashing, cache)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"

[lib]
name = "vitte_incremental"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []
# Option pour sérialiser l'état sur disque
serde   = ["dep:serde", "dep:serde_json"]

[dependencies]
thiserror   = "1"
sha2        = "0.10"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
indexmap    = "2"
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }
log         = "0.4"

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1"