

[package]
name        = "vitte-math"
description = "Bibliothèque mathématique générale pour Vitte (arithmétique, algèbre, trigonométrie, statistiques, nombres complexes)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-math"

keywords   = ["math", "algebra", "statistics", "complex", "trigonometry"]
categories = ["science", "algorithms"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_math"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []
serde   = ["dep:serde", "dep:serde_json"]
approx  = ["dep:approx"]
rand    = ["dep:rand"]

[dependencies]
num-traits = "0.2"
num-complex = "0.4"
approx      = { version = "0.5", optional = true }
rand        = { version = "0.8", optional = true }
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

[dev-dependencies]
rand = "0.8"
pretty_assertions = "1.4"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "approx"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all       = "warn"
pedantic  = "warn"