[package]
name        = "vitte-regex"
description = "Moteur regex pour Vitte : wrappers Rust regex, surcouche syntaxique, intégration Vitte AST."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
documentation = "https://docs.rs/vitte-regex"

keywords   = ["regex", "pattern", "search", "vitte", "dsl"]
categories = ["parsing", "text-processing", "development-tools"]

[lib]
name = "vitte_regex"
path = "src/lib.rs"

[features]
default   = ["std"]
std       = []
perf-literal = []
unicode   = ["dep:regex/unicode"]
syntax    = []

[dependencies]
thiserror = "1.0"
cfg-if    = "1.0"
regex     = { version = "1", default-features = false, features = ["std"] }

[dev-dependencies]
pretty_assertions = "1.4"
proptest = "1.5"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "unicode", "syntax"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all      = "warn"
pedantic = "warn"
