[package]
name        = "vitte-fmt"
description = "Outil de formatage de code source Vitte (style, indentation, normalisation)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-fmt"

keywords   = ["compiler", "formatter", "style", "vitte"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_fmt"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# mode pretty (alignement)
pretty  = []

# JSON output (AST formaté)
json    = ["dep:serde", "dep:serde_json"]

# full
full    = ["std", "pretty", "json"]

[dependencies]
vitte-ast    = { path = "../vitte-ast" }
vitte-parser = { path = "../vitte-parser" }
vitte-errors = { path = "../vitte-errors" }

serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

anyhow = "1.0"

[dev-dependencies]
pretty_assertions = { workspace = true }
insta             = "1.41"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"