[package]
name        = "vitte-opt"
description = "Passes d’optimisation pour Vitte (IR et code généré)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-opt"

keywords   = ["compiler", "optimization", "ir", "vitte"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_opt"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Sérialisation JSON
json = ["dep:serde", "dep:serde_json"]

# Backend LLVM pour certaines passes
llvm = ["dep:inkwell"]

# Tout activé
full = ["std", "json", "llvm"]

[dependencies]
vitte-ir     = { path = "../vitte-ir" }
vitte-errors = { path = "../vitte-errors" }

serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
inkwell    = { version = "0.4", optional = true }

anyhow    = "1.0"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = { workspace = true }
insta             = "1.41"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"