[package]
name         = "vitte-fs"
description  = "Abstractions système de fichiers pour Vitte (I/O, chemins, répertoires)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"

[lib]
name = "vitte_fs"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []
async   = ["tokio/fs"]

[dependencies]
# Sérialisation optionnelle
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

# Gestion des chemins
path-absolutize = "3"

# Support async
tokio = { version = "1", features = ["fs"], optional = true }

# Errors
thiserror = "1"

rand       = "0.8"
filetime   = "0.2"
pathdiff   = "0.2"
dirs-next  = "2"

[dev-dependencies]
tempfile = "3"