[package]
name        = "vitte-progress"
description = "vitte-progress — barres de progression, spinners et compteurs pour CLIs Vitte (ANSI, multithread-safe, indicateurs dynamiques)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["progress", "cli", "bar", "spinner", "vitte"]
categories = ["command-line-interface", "development-tools"]

[lib]
name = "vitte_progress"
path = "src/lib.rs"

[features]
default     = ["std", "ansi", "multi", "indicatif"]
std         = []
alloc-only  = []

serde   = ["dep:serde"]
errors  = ["dep:thiserror"]

# Couleur ANSI
ansi    = ["dep:vitte-ansi"]

# Multi-barres (multi-threads)
multi   = ["dep:crossbeam-channel"]

# Implémentation robuste (indicatif comme backend optionnel)
indicatif = ["dep:indicatif"]

[dependencies]
serde     = { workspace = true, optional = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true, optional = true }

# internes
vitte-ansi = { path = "../vitte-ansi", version = "0.1.0", optional = true }

# externes
crossbeam-channel = { version = "0.5", optional = true }
indicatif         = { version = "0.17", optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile          = "3"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "ansi", "multi", "indicatif", "serde"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"