[package]
name        = "vitte-c"
description = "C FFI pour Vitte : API C stable pour le compilateur et la VM."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
publish      = false

keywords   = ["ffi", "c-api", "compiler", "vm", "vitte"]
categories = ["external-ffi-bindings", "compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name       = "vitte_c"
path       = "src/lib.rs"
crate-type = ["cdylib", "staticlib", "rlib"]

[features]
default = ["std", "ffi-core"]
std     = []

# Surface minimale FFI (types, erreurs)
ffi-core = []

# Expose le pipeline complet (parser→IR→codegen→VM)
ffi-full = ["ffi-core"]

# En-têtes C auto-générés via build.rs + cbindgen
headers = []

[dependencies]
libc           = "0.2"
vitte-ast      = { path = "../vitte-ast", optional = false }
vitte-parser   = { path = "../vitte-parser", optional = false }
vitte-compiler = { path = "../vitte-compiler", optional = false }
vitte-vm       = { path = "../vitte-vm", optional = false }
vitte-errors   = { path = "../vitte-errors", optional = false }

[build-dependencies]
cbindgen = "0.27"

[dev-dependencies]
pretty_assertions = { workspace = true }

[package.metadata.cbindgen]
language = "C"
include_guard = "VITTE_C_H"
pragma_once = true
autogen_warning = "/* This file is generated by cbindgen. Do not edit. */"
cpp_compat = true
usize_is_size_t = true
header = "// Vitte — C API"
trailer = ""
includes = []
no_includes = false
rename = {}

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"