[package]
name        = "vitte-style"
description = "vitte-style — thèmes, styles et mise en forme pour les CLIs Vitte (couleurs, bordures, symboles, palettes, thèmes clairs/sombres)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["style", "theme", "color", "cli", "vitte"]
categories = ["command-line-interface", "development-tools"]

[lib]
name = "vitte_style"
path = "src/lib.rs"

[features]
default     = ["std", "ansi", "errors", "themes"]
std         = []
alloc-only  = []

serde   = ["dep:serde"]
errors  = ["dep:thiserror"]

ansi    = ["dep:vitte-ansi"]
themes  = []

[dependencies]
serde     = { workspace = true, optional = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true, optional = true }

# internes
vitte-ansi = { path = "../vitte-ansi", version = "0.1.0", optional = true }

# externes
palette = { version = "0.7", optional = true } # gestion palettes RGB

[dev-dependencies]
pretty_assertions = { workspace = true }

[package.metadata.docs.rs]
all-features        = false
features            = ["std","ansi","errors","themes","serde"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
doc_markdown            = "allow"
too_many_lines          = "allow"