[package]
name = "vitte-linker"
version = "0.1.0"
edition = "2021"

[dependencies]
vitte-ir = { path = "../vitte-ir" }
inkwell = { version = "0.4", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[features]
default = ["std", "json"]
std     = []

# Intégration avec LLVM
llvm = ["dep:inkwell"]

# Sérialisation JSON
json  = ["dep:serde", "dep:serde_json"]
# Alias pour compat' avec les attributs #[cfg(feature = "serde")] présents dans le code
serde = ["json"]

# Tout activé
full = ["std", "llvm", "json"]