[package]
name = "vitte-tools"
version = "0.1.0"
description = "Outils CLI du langage Vitte (asm, disasm, link, fmt, repl)"
# Hérite des métadonnées du workspace
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
repository.workspace    = true
homepage.workspace      = true
documentation.workspace = true
keywords.workspace      = true
categories.workspace    = true

[lib]
name = "vitte_tools"
path = "src/lib.rs"
crate-type = ["rlib"]

# ───────────────────────────── Features
[features]
# Par défaut : couleurs, config du formatter, JSON
default = ["colors", "fmt-config", "serde"]

# Couleurs (yansi)
colors = ["dep:yansi"]

# Config du formatter via .vittefmt.toml
fmt-config = ["dep:toml", "dep:serde"]

# Sorties JSON (disasm/link manifest) + relaie vers vitte-core
serde = ["dep:serde", "dep:serde_json", "vitte-core/serde"]

# Emplacement d'historique (REPL) dans le répertoire utilisateur
dirs = ["dep:dirs-next"]

# VM complète (REPL)
vm = ["dep:vitte-vm"]

# Tracing (optionnel)
tracing = ["dep:tracing"]

# Gating des binaires (évite d’échouer si les fichiers bin ne sont pas encore présents)
bin-asm = []
bin-disasm = []
bin-link = []
bin-fmt = []
bin-repl = []

# ───────────────────────────── Dépendances
[dependencies]
# Workspace deps
anyhow             = { workspace = true }
clap               = { workspace = true, features = ["derive"] }
serde              = { workspace = true, optional = true }
serde_json         = { workspace = true, optional = true }
toml               = { workspace = true, optional = true }
tracing            = { workspace = true, optional = true }

# Non-workspace deps (versions explicites)
camino     = "1"
color-eyre = "0.6"
yansi      = { version = "1", optional = true }
dirs-next  = { version = "2", optional = true }
rustyline  = "14"

# Crates internes
vitte-core     = { path = "../vitte-core" }              # la feature `serde` se pilote via la feature locale `serde`
vitte-compiler = { path = "../vitte-compiler" }
vitte-vm       = { path = "../vitte-vm", optional = true }

# ───────────────────────────── Binaries (gated)
[[bin]]
name = "vitte-asm"
path = "src/bin/vitte-asm.rs"
required-features = ["bin-asm"]

[[bin]]
name = "vitte-disasm"
path = "src/bin/vitte-disasm.rs"
required-features = ["bin-disasm"]

[[bin]]
name = "vitte-link"
path = "src/bin/vitte-link.rs"
required-features = ["bin-link"]

[[bin]]
name = "vitte-fmt"
path = "src/bin/vitte-fmt.rs"
required-features = ["bin-fmt"]

[[bin]]
name = "vitte-repl"
path = "src/bin/vitte-repl.rs"
required-features = ["bin-repl"]

[package.metadata.docs.rs]
all-features = true
