[package]
name        = "vitte-metrics"
description = "Collecte et exposition de métriques pour le compilateur et la VM Vitte (profilage, télémétrie)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-metrics"

keywords   = ["compiler", "metrics", "profiling", "telemetry", "vitte"]
categories = ["development-tools", "profiling"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_metrics"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Export JSON
json = ["dep:serde", "dep:serde_json"]

# Export Prometheus
prometheus = ["dep:prometheus"]

# Tout activé
full = ["std", "json", "prometheus"]

[dependencies]
lazy_static = "1.5"
parking_lot = "0.12"

serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
prometheus = { version = "0.13", optional = true }

anyhow = "1.0"

[dev-dependencies]
pretty_assertions = { workspace = true }
insta             = "1.41"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"