[package]
name = "vitte-cs2d"
description = "Utilitaires 2D compacts et solides pour Vitte : vecteurs, matrices, géométrie, collisions, spatial hash, pathfinding A*, RNG."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vitte-lang/vitte"
homepage   = "https://github.com/vitte-lang/vitte"
readme     = "README.md"
keywords   = ["vitte", "2d", "math", "geometry", "pathfinding", "game"]
categories = ["game-development", "mathematics", "data-structures"]

[lib]
name = "vitte_cs2d"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std     = []        # active HashMap, HashSet
f64     = []        # utilise f64 au lieu de f32
serde   = ["dep:serde"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"
