[package]
name = "vitte-fronted-llvm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "LLVM backend scaffold for Vitte."
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://vitte-lang.github.io/vitte/"

[lib]
name = "vitte_fronted_llvm"
path = "src/lib.rs"

[dependencies]