[package]
name = "vitte-profiler"
version = "0.1.0"
edition = "2021"

[features]
default = []
serde = ["dep:serde"]                 # <- supprime les warnings "unexpected cfg value: serde"
json  = ["serde", "dep:serde_json"]   # pour to_json()
chrome = ["serde", "dep:serde_json"]  # pour to_chrome_trace()
full = ["serde", "json", "chrome"]

[dependencies]
once_cell = "1"            # <- corrige E0433 (Lazy)
parking_lot = "0.12"

serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }