[package]
name        = "vitte-install"
description = "Outil d’installation et de gestion des toolchains Vitte (semblable à rustup pour Rust)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-install"

keywords   = ["compiler", "installer", "toolchain", "vitte"]
categories = ["development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[[bin]]
name = "vitte-install"
path = "src/main.rs"

[lib]
name = "vitte_install"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Support du format JSON pour manifestes
json = ["dep:serde", "dep:serde_json"]

# Téléchargement via reqwest
net = ["dep:reqwest"]

# Extraction archives (tar/zip)
archive = ["dep:tar", "dep:flate2", "dep:zip"]

# Tout activé
full = ["std", "json", "net", "archive"]

[dependencies]
anyhow   = "1.0"
dirs     = "5.0"
tokio    = { version = "1.41", features = ["full"], optional = true }
reqwest  = { version = "0.12", optional = true }
tar      = { version = "0.4", optional = true }
flate2   = { version = "1.0", optional = true }
zip      = { version = "0.6", optional = true }

serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
assert_cmd         = "2.0"
predicates         = "3.1"
pretty_assertions  = { workspace = true }
tempfile           = "3.12"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"