[package]
name        = "vitte-net"
description = "Réseau pour Vitte : sockets async, HTTP/WS clients, TLS (rustls|native-tls), DNS, utilitaires."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
documentation = "https://docs.rs/vitte-net"

keywords   = ["network", "http", "websocket", "tls", "async"]
categories = ["network-programming", "asynchronous", "development-tools"]

[lib]
name = "vitte_net"
path = "src/lib.rs"

[features]
# Par défaut, support std + runtime tokio + rustls
default      = ["std", "rt-tokio", "tls-rustls"]
std          = []

# Sélection du runtime (mutuellement exclusifs en pratique)
rt-tokio     = ["dep:tokio", "tokio/net", "tokio/time", "tokio/sync"]
rt-async-std = ["dep:async-std"]
rt-smol      = ["dep:smol"]

# Pile HTTP client (hyper) optionnelle
http         = ["dep:hyper", "dep:http", "dep:h2"]
# WebSockets optionnels
ws           = ["dep:tokio-tungstenite", "dep:tungstenite"]

# TLS (choisir l’un)
tls-rustls   = ["dep:rustls", "dep:rustls-native-certs"]
tls-native   = ["dep:native-tls"]

# Sérialisation JSON optionnelle
serde        = ["dep:serde", "dep:serde_json"]

[dependencies]
thiserror = "1.0"
cfg-if    = "1.0"
http      = { version = "1", optional = true }
h2        = { version = "0.4", optional = true }
hyper     = { version = "1", optional = true, features = ["http1", "http2", "client"] }

# runtimes
tokio      = { version = "1.39", optional = true, default-features = false, features = ["rt", "rt-multi-thread", "macros", "net", "time", "sync"] }
async-std  = { version = "1.13", optional = true, features = ["attributes"] }
smol       = { version = "2.0", optional = true }

# websockets
tokio-tungstenite = { version = "0.23", optional = true }
tungstenite       = { version = "0.21", optional = true }

# tls
rustls              = { version = "0.23", optional = true, default-features = false, features = ["ring", "std"] }
rustls-native-certs = { version = "0.7",  optional = true }
native-tls          = { version = "0.2",  optional = true }

# serde
serde      = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
bytes = "1"