[package]
name        = "vitte-regalloc"
description = "Allocation de registres pour Vitte (IR -> code machine optimisé)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-regalloc"

keywords   = ["compiler", "register-allocation", "backend", "vitte"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_regalloc"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Sérialisation JSON
json = ["dep:serde", "dep:serde_json"]

# Algo graphique (graph coloring)
graph = []

# Algo linéaire (linear scan)
linear = []

# Tout activé
full = ["std", "json", "graph", "linear"]

[dependencies]
vitte-ir     = { path = "../vitte-ir" }
vitte-errors = { path = "../vitte-errors" }

serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

anyhow    = "1.0"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"