[package]
name        = "vitte-channel"
description = "Canaux de communication concurrents pour Vitte (MPSC, SPSC, broadcast, async)"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-channel"

keywords   = ["vitte", "concurrency", "channel", "mpsc", "async"]
categories = ["concurrency", "data-structures", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_channel"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default   = ["std"]
std       = []
async     = ["tokio", "futures"]

[dependencies]
parking_lot       = "0.12"
crossbeam-channel = "0.5"
futures           = { version = "0.3", optional = true }
tokio             = { version = "1", features = ["sync"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }