[package]
name = "vitte-stdlib-ultimate"
version = "0.1.0"
description = "Extended standard library for Vitte"
authors = ["Vitte Team"]
license = "MIT"

[lib]
path = "modules"

[features]
default = ["core","math","sys","net","concurrent","formats","crypto","utils"]

[feature.core]
[feature.math]
[feature.sys]
[feature.net]
[feature.concurrent]
[feature.formats]
[feature.crypto]
[feature.utils]
