[package]
name         = "vitte-http"
description  = "Client/serveur HTTP pour Vitte (basé sur hyper/reqwest, support async)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"

[lib]
name = "vitte_http"
path = "src/lib.rs"

[features]
default = ["client", "server"]
std     = []
# Client HTTP via reqwest
client  = ["reqwest"]
# Serveur HTTP via hyper
server  = ["hyper", "tokio"]

[dependencies]
thiserror = "1"
tokio     = { version = "1", features = ["rt-multi-thread", "macros"], optional = true }
hyper     = { version = "1", features = ["full"], optional = true }
reqwest   = { version = "0.12", features = ["json", "gzip", "brotli"], optional = true }
serde     = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
log       = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }