

[package]
name = "vitte-fronted"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Frontend core layer for the Vitte compiler (shared logic for LLVM/WASM backends)."
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://vitte-lang.github.io/vitte/"
readme = "README.md"
categories = ["compilers", "development-tools"]
keywords = ["vitte", "frontend", "compiler"]

[lib]
name = "vitte_fronted"
path = "src/lib.rs"

[dependencies]
anyhow = "1"

[dev-dependencies]
pretty_assertions = "1"