

[package]
name        = "vitte-verify"
description = "Vérification pour Vitte : signatures, hachages, intégrité, validation de dépendances, attestations."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
documentation = "https://docs.rs/vitte-verify"

keywords   = ["verify", "signature", "hash", "integrity", "attestation"]
categories = ["cryptography", "security", "development-tools"]

[lib]
name = "vitte_verify"
path = "src/lib.rs"

[features]
default   = ["std", "hash", "signature"]
std       = []
hash      = ["dep:sha2", "dep:blake3", "dep:hex"]
signature = ["dep:ed25519-dalek", "dep:pkcs8", "dep:x509-cert"]
serde     = ["dep:serde", "dep:serde_json"]

[dependencies]
thiserror = "1.0"
cfg-if    = "1.0"

# Hash
sha2    = { version = "0.10", optional = true }
blake3  = { version = "1.5", optional = true }
hex     = { version = "0.4", optional = true }

# Signature
ed25519-dalek = { version = "2", optional = true }
pkcs8         = { version = "0.10", optional = true }
x509-cert     = { version = "0.2", optional = true }

# Serde
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

[dev-dependencies]
pretty_assertions = "1.4"
serde_json = "1"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "hash", "signature", "serde"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all      = "warn"
pedantic = "warn"