[package]
name        = "vitte-typer"
description = "Système de typage pour Vitte (inférence, vérification, contraintes)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-typer"

keywords   = ["compiler", "type-system", "inference", "checker", "vitte"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_typer"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Export JSON du graphe de types
json = ["dep:serde", "dep:serde_json"]

# Tout activé
full = ["std", "json"]

[dependencies]
vitte-errors = { path = "../vitte-errors" }
vitte-ast    = { path = "../vitte-ast" }
vitte-hir    = { path = "../vitte-hir" }

anyhow    = "1.0"
thiserror = "1.0"
indexmap  = "2.5"
ena       = "0.14"   # unification / solver de contraintes

serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
insta             = "1.41"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
doc_markdown            = "allow"
too_many_lines          = "allow"