[package]
name        = "vitte-package"
description = "Gestionnaire de paquets et métadonnées pour l’écosystème Vitte."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["package", "registry", "metadata", "vitte"]
categories = ["development-tools", "compilers"]

[lib]
name = "vitte_package"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

# Futures fonctionnalités
cli         = []
resolver    = []

full = ["std", "cli", "resolver"]

[dependencies]
serde      = { workspace = true, optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
too_many_lines          = "allow"
doc_markdown            = "allow"
