[package]
name = "vitte-table"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Table utilities for Vitte."
repository = "https://github.com/vitte-lang/vitte"

[lib]
name = "vitte_table"
path = "src/lib.rs"

[dependencies]

[features]
default     = ["std"]
std         = []
alloc-only  = []
serde       = []
errors      = []
ansi        = []
style       = []
wrap        = []
csv         = []
widths      = []