[package]
name        = "vitte-table"
description = "vitte-table — rendu de tableaux pour CLIs Vitte (alignements, largeurs Unicode, bordures ASCII/UTF, wrap, CSV/TSV I/O, export Markdown)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["table", "cli", "unicode", "wrap", "vitte"]
categories = ["command-line-interface", "text-processing", "development-tools"]

[lib]
name = "vitte_table"
path = "src/lib.rs"

[features]
default   = ["std", "errors", "serde", "ansi", "style", "wrap", "widths", "markdown"]
std       = []
alloc-only = []

# Ergonomie
serde   = ["dep:serde"]
errors  = ["dep:thiserror"]
ansi    = ["dep:vitte-ansi"]
style   = ["dep:vitte-style"]

# Calculs de largeur et segmentation Unicode
widths  = ["dep:unicode-width", "dep:unicode-segmentation"]

# Mise en page
wrap    = ["dep:textwrap"]

# I/O tabulaire
csv     = ["dep:csv"]
tsv     = ["csv"]                         # alias logique (CSV avec délimiteur \t)

# Export Markdown (génération simple, pas de dépendance)
markdown = []

# Backend optionnel (accès direct pour features avancées)
backend-comfy = ["dep:comfy-table"]

[dependencies]
# internes
vitte-ansi  = { path = "../vitte-ansi",  version = "0.1.0", optional = true }
vitte-style = { path = "../vitte-style", version = "0.1.0", optional = true }

# externes
serde     = { workspace = true, optional = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true, optional = true }

unicode-width         = { version = "0.1", optional = true }
unicode-segmentation  = { version = "1.11", optional = true }
textwrap              = { version = "0.16", optional = true, default-features = false, features = ["unicode-width"] }

csv                   = { version = "1.3", optional = true }

comfy-table           = { version = "7", optional = true, default-features = false, features = ["tty", "unicode-width"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
indoc             = "2"

[package.metadata.docs.rs]
all-features        = false
features            = ["std","errors","serde","ansi","style","wrap","widths","markdown","csv","backend-comfy"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"