[package]
name        = "vitte-cache"
description = "Système de cache multi-stratégies (mémoire, disque, distribué) pour Vitte"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-cache"

keywords   = ["vitte", "cache", "memoization", "storage", "distributed"]
categories = ["compilers", "development-tools", "caching"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_cache"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default     = ["std"]
std         = []
disk        = ["serde", "serde_json"]
distributed = ["serde", "serde_json"]

[dependencies]
serde        = { version = "1", features = ["derive"], optional = true }
serde_json   = { version = "1", optional = true }
thiserror    = "1"
parking_lot  = "0.12"
ahash        = "0.8"

[dev-dependencies]
tempfile = "3"
tokio     = { version = "1", features = ["rt-multi-thread", "macros", "time"] }